pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                dir('demo.project'){
                    echo 'building application'
                }
                
            }
        }
        stage('test'){
            steps{
                dir('demo.project'){
                    echo 'testing application throughly'
                }
                
            }
        }
        stage('deploye'){
            steps{
                dir('demo.project'){
                    echo 'deployinh th application'
                }
                
            }
        }
    }
}