pipeline{
    agent any
    stages{
        stage('Build'){
            agent { label 'java-agent'}
            steps{
                dir('demo.project'){
                    echo 'building application'
                }
                
            }
        }
        stage('test'){
            agent {label 'testing-agent'}
            steps{
                dir('demo.project'){
                    echo 'testing application throughly'
                }
                
            }
        }
        stage('deploye'){
            agent {label 'deployment-agent'}
            steps{
                dir('demo.project'){
                    echo 'deployinh th application'
                }
                
            }
        }
    }
}