pipeline {
    agent { label 'built-in' }
    environment {
        REGISTRY_CREDENTIALS = credentials('docker-hub-creds')
        REGISTRY_URL = 'docker.io'
        IMAGE_NAME = "tanbieee/my-two-demo-project"
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }
    stages{
        stage('checkout'){
            steps{
                dir('two.demo.project'){
                    echo 'checking out the code from git repository...'
                    checkout scm
                }
            }
        }
        stage('build & test'){
            steps{
                dir('two.demo.project'){
                    echo 'running build and test stages...'
                        bat 'mvn clean package -DskipTests'
                }
            }
        }
        stage('build docker image'){
            steps{
                dir('two.demo.project'){
                    echo "building the docker image..."
                    bat "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }
        stage('dockerr login and push'){
            steps{
                dir('two.demo.project'){
                    echo 'logging in to Docker registry...'
                    bat 'docker login %REGISTRY_URL% -u %REGISTRY_CREDENTIALS_USR% -p %REGISTRY_CREDENTIALS_PSW%'
                    echo 'pushing the docker image to registry...'
                    bat "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest"
                    bat "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                    bat "docker push ${IMAGE_NAME}:latest"
                }
            }
        }
    }
}
