pipeline{
    agent {label 'built-in'}
    environment{
        DOCKER_IMAGE = "tanbieee/my-two-demo-project"
        REGISTRY_CREDENTIALS = credentials('dockerhub-cred')
    }
    stages{
        stage('build & test'){
            steps{
                dir('two.demo.project'){
                    echo 'running building stage in devops branch...'
                    echo 'compiling and validating the stage...'
                    echo 'this is the test phase in devops branch...'
                    echo 'testing the repository....'
                }
            }
        }
        stage('deploy'){
            steps{
                dir('two.demo.project'){
                    echo 'this is the last step of deployment in devops branch...'
                    echo 'deployed done'
                }
            }
        }
        stage('Docker Build Tag & Push'){
            steps{
                script{
                    withEnv({
                        'DOCKER_USER=tanbieee',
                        'DOCKER_PASS=T@nvi_2004'
                    }){
                        dir('two.demo.project'){
                            echo 'loggin into DOcker hub...'
                            sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"
                            echo 'Building the docker image...'
                            def myImage = docker.build("${DOCKER_IMAGE}:${BUILD_NUMBER}")
                            echo 'pusing the image to dockr hub...'
                            myImage.push()
                        }
                    }
                }
                
            }
        }
    }
}