pipeline {
    agent { label 'built-in' }
    environment {
        DOCKER_IMAGE = "tanbieee/my-two-demo-project"
    }
    stages {
        stage('build & test') {
            steps {
                dir('two.demo.project') {
                    echo 'running building stage in devops branch...'
                    echo 'compiling and validating the stage...'
                    echo 'this is the test phase in devops branch...'
                    echo 'testing the repository....'
                }
            }
        }
        stage('deploy') {
            steps {
                dir('two.demo.project') {
                    echo 'this is the last step of deployment in devops branch...'
                    echo 'deployed done'
                }
            }
        }
        stage('Docker Build Tag & Push') {
            steps {
                dir('two.demo.project') {
                    echo 'Logging into Docker Hub...'
                    
                    // This block strips any hidden trailing spaces or returns on Windows
                    withCredentials([string(credentialsId: 'DOCKER_PASS', variable: 'RAW_PASS')]) {
                        bat """
                        @echo off
                        <nul set /p="%RAW_PASS%" > token.txt
                        type token.txt | docker login -u tanbieee --password-stdin
                        del token.txt
                        """
                    }

                    echo 'Building the Docker Image...'
                    bat "docker build -t %DOCKER_IMAGE%:%BUILD_NUMBER% ."

                    echo 'Tagging image as latest...'
                    bat "docker tag %DOCKER_IMAGE%:%BUILD_NUMBER% %DOCKER_IMAGE%:latest"

                    echo 'Pushing build number tag...'
                    bat "docker push %DOCKER_IMAGE%:%BUILD_NUMBER%"
                    
                    echo 'Pushing latest tag...'
                    bat "docker push %DOCKER_IMAGE%:latest"
                    
                    echo 'Logging out...'
                    bat "docker logout"
                }
            }
        }

    }
}
