name: java maven ci
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository code
      uses: actions/checkout@v4

    - name: Initialize java environment
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and test application
      run: mvn -B clean package